### ISSUE TITLE
Complex objects in classes

### ISSUE THREAD

**Issue by haroon407** [eeyang92/class-to-mongoose-schema#1]
The package works fine for simple data types for the class attributes but not for objects such as:

I have a class called search which contains a list of result objects. When I try to run the code my application crashes with the following error:

"
/node_modules/mongoose/lib/schema.js:641
        throw new TypeError('Undefined type `' + name + '` at array `' + path +
        ^

TypeError: Undefined type `Result` at array `result`
    at Function.Schema.interpretAsType (/Users/haroon/ccc/backend/node_modules/mongoose/lib/schema.js:641:15)
    at Schema.path (/Users/haroon/ccc/backend/node_modules/mongoose/lib/schema.js:525:29)
    at Schema.add (/Users/haroon/ccc/backend/node_modules/mongoose/lib/schema.js:407:12)
    at new Schema (/Users/haroon/ccc/backend/node_modules/mongoose/lib/schema.js:105:10)
    at Object.classToSchema [as default] (/Users/haroon/ccc/backend/node_modules/class-to-mongoose-schema/dist/index.js:67:15)
    at Object.<anonymous> (/Users/haroon/ccc/backend/dist/models/search.js:104:56)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/haroon/ccc/backend/dist/api/search/endpoints.js:18:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
Application has crashed!
"
 

Here;s a short example of my code:

export class Search{
searchName = String;
searchVersion = Number;
result = [Result];

}

class Result {
    name = String;
    level = Number;
    length = Number;
}

**Comment by eeyang92** [comment]
Hi @haroon407, sorry I didn't see this until now - this project is no longer being actively maintained as I have realized that relational databases suit my needs much better.

However, if you would like to submit a pull request I would gladly review it.
